name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: dotnet test
      run: dotnet test
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v1.2
      with:
        buildCommand: dotnet build
        testCommand: dotnet test 
        projectKey: a-project-key
        projectName: a-project-name
        sonarOrganisation: raknas999
        beginArguments: /d:sonar.verbose="true" /d:sonar.cs.opencover.reportsPaths="/path/to/coverage.xml" /d:sonar.coverage.exclusions="**/*.cs"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
